### PR TITLE
Fix ability to add multiple command manager groups

### PR DESCRIPTION
**Pull request by brinkdinges**
Made the tabs property static so it's possible to add multiple groups to a single command manager tab.

### CODE REVIEW

**Comment by angelsix** [comment]
Not sure on this one. Due to the AppDomain issue with SW (hence the issue with the IoC being the same instance for any plugin using SolidDNA we really need to think carefully and probably completely remove any static instances anywhere. This will share between all plug-ins.

Can you test it first, run 2 SoildDNA add-ins and see if they share this static list.

**Comment by brinkdinges** [comment]
Good one. I'll await your results on running multiple add-ins and revisit this PR afterward.

**Comment by emersonbottero** [comment]
it's just me or is @angelsix  waiting for @brinkdinges  to test 
and 
@brinkdinges  is waiting @angelsix to test?

🤔

**Comment by brinkdinges** [comment]
I was waiting for the ability to run multiple add-ins at the same time, before continuing with this minor improvement.

I have seen multiple commits from Angelsix towards this goal, but no confirmation that it is done. I have also been so busy with customer projects that I had no time to really check. I have blocked out this week for my own products, so I'd love to make some progress with SolidDna.

**Pull request closed without merging**
